2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_setup.py:_flush():76] Configure stats pid to 22121
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_setup.py:_flush():76] Loading settings from /home/ale/.config/wandb/settings
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_setup.py:_flush():76] Loading settings from /home/ale/TT_RLProject_2024/wandb/settings
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'cm_datascience', 'entity': 'cm_datascience', 'root_dir': '/home/ale/TT_RLProject_2024', 'run_id': 'v17aj2tk', 'sweep_param_path': '/home/ale/TT_RLProject_2024/wandb/sweep-9vkysbcr/config-v17aj2tk.yaml', 'sweep_id': '9vkysbcr'}
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'Task_4/WANDB_v1.py', 'program_abspath': '/home/ale/TT_RLProject_2024/Task_4/WANDB_v1.py', 'program': '/home/ale/TT_RLProject_2024/Task_4/WANDB_v1.py'}
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_init.py:_log_setup():520] Logging user logs to /home/ale/TT_RLProject_2024/wandb/run-20240612_194345-v17aj2tk/logs/debug.log
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_init.py:_log_setup():521] Logging internal logs to /home/ale/TT_RLProject_2024/wandb/run-20240612_194345-v17aj2tk/logs/debug-internal.log
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_init.py:init():560] calling init triggers
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_init.py:init():568] wandb.init called with sweep_config: {'batch_size': 64, 'clip_range': 0.1, 'ent_coef': 0, 'gamma': 0.95, 'learning_rate': 0.0001, 'n_epochs': 10, 'n_steps': 1024, 'vf_coef': 0.65}
config: {}
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_init.py:init():610] starting backend
2024-06-12 19:43:45,492 INFO    Thread-8  :22121 [wandb_init.py:init():614] setting up manager
2024-06-12 19:43:45,494 INFO    Thread-8  :22121 [backend.py:_multiprocessing_setup():107] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-12 19:43:45,495 INFO    Thread-8  :22121 [wandb_init.py:init():622] backend started and connected
2024-06-12 19:43:45,498 INFO    Thread-8  :22121 [wandb_run.py:_config_callback():1382] config_cb None None {'batch_size': 64, 'clip_range': 0.1, 'ent_coef': 0, 'gamma': 0.95, 'learning_rate': 0.0001, 'n_epochs': 10, 'n_steps': 1024, 'vf_coef': 0.65}
2024-06-12 19:43:45,499 INFO    Thread-8  :22121 [wandb_init.py:init():711] updated telemetry
2024-06-12 19:43:45,509 INFO    Thread-8  :22121 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-12 19:43:46,333 INFO    Thread-8  :22121 [wandb_run.py:_on_init():2402] communicating current version
2024-06-12 19:43:46,377 INFO    Thread-8  :22121 [wandb_run.py:_on_init():2411] got version response 
2024-06-12 19:43:46,377 INFO    Thread-8  :22121 [wandb_init.py:init():795] starting run threads in backend
2024-06-12 19:43:46,713 INFO    Thread-8  :22121 [wandb_run.py:_console_start():2380] atexit reg
2024-06-12 19:43:46,713 INFO    Thread-8  :22121 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2024-06-12 19:43:46,713 INFO    Thread-8  :22121 [wandb_run.py:_redirect():2300] Wrapping output streams.
2024-06-12 19:43:46,713 INFO    Thread-8  :22121 [wandb_run.py:_redirect():2325] Redirects installed.
2024-06-12 19:43:46,714 INFO    Thread-8  :22121 [wandb_init.py:init():838] run started, returning control to user process
2024-06-12 19:43:46,844 INFO    Thread-8  :22121 [wandb_run.py:_finish():2109] finishing run cm_datascience/cm_datascience/v17aj2tk
2024-06-12 19:43:46,844 INFO    Thread-8  :22121 [wandb_run.py:_atexit_cleanup():2349] got exitcode: 1
2024-06-12 19:43:46,845 INFO    Thread-8  :22121 [wandb_run.py:_restore():2332] restore
2024-06-12 19:43:46,845 INFO    Thread-8  :22121 [wandb_run.py:_restore():2338] restore done
2024-06-12 19:43:50,143 INFO    Thread-8  :22121 [wandb_run.py:_restore():2332] restore
2024-06-12 19:43:50,143 INFO    Thread-8  :22121 [wandb_run.py:_restore():2338] restore done
2024-06-12 19:43:51,145 ERROR   Thread-8  :22121 [wandb_run.py:_atexit_cleanup():2370] Problem finishing run
Traceback (most recent call last):
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/site-packages/wandb/agents/pyagent.py", line 307, in _run_job
    self._function()
  File "/home/ale/TT_RLProject_2024/Task_4/WANDB_v1.py", line 43, in train
    wandb_callback = WandbEvalCallback(eval_env, n_eval_episodes=10, eval_freq=1000, verbose=1)
TypeError: __init__() got an unexpected keyword argument 'n_eval_episodes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 2358, in _atexit_cleanup
    self._on_finish()
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 2623, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
Exception
